version: "3.9"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/home/jovyan/
    environment:
      - JUPYTER_ENABLE_LAB=1
    ports:
     - "8000:8888"
    restart: always